# services:
#   app:
#     image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
#     command: ["npm", "start"]
#     secrets:
#       - AWS_REGION
#       - AWS_S3_BUCKET_NAME
#     environment:
#       AWS_REGION_FILE: /run/secrets/AWS_REGION
#       AWS_S3_BUCKET_NAME_FILE: /run/secrets/AWS_S3_BUCKET_NAME
#     ports:
#       - 5000:5000
# secrets:
#   AWS_REGION:
#     file: ./path/to/aws_region
#   AWS_S3_BUCKET_NAME:
#     file: ./path/to/aws_s3_bucket_name

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    secrets:
      - secret_message
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      - NGINX_SECRET_MESSAGE_FILE=/run/secrets/secret_message
    command: /bin/bash -c "echo 'Fun with Docker Compose!' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  # A fun Alpine container that just pings the web server
  pinger:
    image: alpine:latest
    depends_on:
      - web
    secrets:
      - secret_message
    environment:
      - SECRET_MESSAGE_FILE=/run/secrets/secret_message
    command: /bin/sh -c "apk add --no-cache curl && sleep 5 && curl -s http://web:80 && echo '\nSecret message:' && cat /run/secrets/secret_message"

secrets:
  secret_message:
    file: ./secrets/secret_message.txt
