name: CI with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (optional, for advanced builds)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      # 3. Log in to Docker Hub (if pushing images)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and push Docker images using Docker Compose
      - name: Build Docker Compose services
        run: docker compose -f ./docker-compose.yml build

      # 5. (Optional) Run tests or other commands
      - name: Run tests
        run: docker compose run --rm pinger

      # 6. (Optional) Bring down services
      - name: Tear down Docker Compose
        run: docker compose down
